<a href="https://colab.research.google.com/github/KieranJP/SVM-Classifier/blob/master/SVM_Classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#Uploading Test Data
from google.colab import files
uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

Saving FullELFFDataset.csv to FullELFFDataset (1).csv
User uploaded file "FullELFFDataset.csv" with length 14744861 bytes

In [0]:
#Imports
from matplotlib import pyplot as plt
%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix

#Selecting the Csv to use then Displaying it, may have to change the (3) when first ran.
import pandas as pd
df = pd.read_csv("FullELFFDataset.csv")
#2800 Rows vs 40 Columns
df[0:10]

   numberOfMethods      lcom      avcc   ...  mod   NumberOfDefects   Defective
0                11  0.000000  5.545455  ...     0                 0      False
1                 4  0.583333  4.000000  ...     1                 0      False
2                 1  0.000000  1.000000  ...     1                 0      False
3                22  0.023810  1.909091  ...     0                 0      False
4                 1  0.000000  1.000000  ...     1                 0      False
5                 4  0.000000  1.500000  ...     1                 0      False
6                 4  0.000000  2.250000  ...     0                 0      False
7                 1  0.000000  1.000000  ...     1                 0      False
8                13  0.018519  4.615385  ...     0                 3       True
9                11  0.200000  5.181818  ...     0                 0      False

[10 rows x 40 columns]

In [0]:
#Setting up the dataframes so that ones with defects get placed in dataframe1 and ones without get placed in dataframe0.
df0 = df[df.Defective==False]
df1 = df[df.Defective==True]

#Dropping the classification so it can be predicted
X = df.drop(['Defective'], axis='columns')
Y = df.Defective

X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.2)
trueWeight = len(Y_train[Y_train==False])
falseWeight = len(Y_train[Y_train==True])

print("Y_train 'False' Length:", len(Y_train[Y_train==False]))
print("Y_train 'True' Length:", len(Y_train[Y_train==True]))

Y_train 'False' Length: 74572
Y_train 'True' Length: 3892

In [0]:
from sklearn.metrics import classification_report, confusion_matrix 
from sklearn import preprocessing
X = preprocessing.scale(X) 

model = SVC(kernel='linear', verbose=10)

#Training the Model using the fit method - Change these parameters to tune the model
model.fit(X_train, Y_train)

Y_predict = model.predict(X_test)
print(confusion_matrix(Y_test, Y_predict))
print(classification_report(Y_test, Y_predict))

[LibSVM]

In [0]:
Y_predict = model.predict(X_test)
cfm = confusion_matrix(Y_test, Y_predict)

print(cfm)
trueNeg = cfm[0,0]
falseNeg = cfm[1,0]
truePos = cfm[1,1]
falsePos = cfm[0,1]

#True Positive Rate
truePosRate = truePos/(truePos+falseNeg)
print("TruePos", truePosRate)

#True Negative Rate
trueNegRate = trueNeg/(trueNeg+falsePos)
print("TrueNeg", trueNegRate)

#Positive Prediciton Value - Pos Precision
posPreVal = truePos/(truePos+falsePos)
print("PosPrecision", posPreVal)

#Negative Prediciton Value - Neg Precision
negPreVal = trueNeg/(trueNeg+falseNeg)
print("NegPrecision", negPreVal)